from __future__ import annotations

from collections import defaultdict
from pathlib import Path, PurePosixPath
from typing import Any

from .detect import COMPONENT_MARKERS
from .file_coverage import build_file_coverage_report
from ..core.models import ProjectProfile
from ..core.paths import is_inside_root, path_from_relative_text

SCHEMA_VERSION = "harnessforge.index.v1"
MAX_EXAMPLES = 20
TEXT_PROBE_BYTES = 8192
FILE_CLASS_ORDER = (
    "source",
    "test",
    "docs",
    "generated",
    "vendor",
    "workflow",
    "harness",
    "config",
    "sbom",
    "other",
)

SOURCE_LANGUAGES = {
    "cpp",
    "dotnet",
    "go",
    "java",
    "javascript",
    "php",
    "python",
    "ruby",
    "rust",
    "shell",
    "starlark",
    "swift",
    "terraform",
    "typescript",
}
LANGUAGE_BY_SUFFIX = {
    ".adoc": "docs",
    ".bash": "shell",
    ".bzl": "starlark",
    ".c": "cpp",
    ".cc": "cpp",
    ".cjs": "javascript",
    ".cpp": "cpp",
    ".cs": "dotnet",
    ".cxx": "cpp",
    ".fs": "dotnet",
    ".go": "go",
    ".h": "cpp",
    ".hpp": "cpp",
    ".java": "java",
    ".js": "javascript",
    ".json": "json",
    ".jsx": "javascript",
    ".kt": "java",
    ".kts": "java",
    ".md": "docs",
    ".mjs": "javascript",
    ".php": "php",
    ".ps1": "powershell",
    ".py": "python",
    ".rb": "ruby",
    ".rs": "rust",
    ".rst": "docs",
    ".scl": "starlark",
    ".sh": "shell",
    ".swift": "swift",
    ".tf": "terraform",
    ".toml": "toml",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".txt": "docs",
    ".vb": "dotnet",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".zsh": "shell",
}
TEXT_SUFFIXES = frozenset(LANGUAGE_BY_SUFFIX) | {
    ".cfg",
    ".conf",
    ".ini",
    ".lock",
    ".properties",
    ".xml",
}
VENDOR_PARTS = {
    "3rdparty",
    "external",
    "third-party",
    "third_party",
    "vendor",
    "vendors",
}
GENERATED_PARTS = {
    "autogen",
    "generated",
    "gen",
}
GENERATED_NAME_MARKERS = (
    ".generated.",
    "_generated.",
    "generated_",
    "generated-",
)
GENERATED_TEXT_MARKERS = (
    "@generated",
    "code generated",
    "do not edit",
    "generated by",
    "this file was generated",
)
INSTRUCTION_FILES = {
    ".github/copilot-instructions.md",
    "AGENTS.md",
    "CLAUDE.md",
    "GEMINI.md",
}
SOURCE_OF_TRUTH_NAMES = {
    "architecture.md",
    "architecture.rst",
    "design.md",
    "design.rst",
    "foundation.md",
    "overview.md",
    "product.md",
    "readme.md",
    "requirements.md",
    "security.md",
    "vision.md",
}
SOURCE_OF_TRUTH_PARTS = {
    ".specify",
    "architecture",
    "design",
    "docs",
    "requirements",
    "specs",
}
ENTRYPOINT_NAMES = {
    "Dockerfile",
    "Containerfile",
    "Justfile",
    "Makefile",
    "action.yaml",
    "action.yml",
    "docker-compose.yaml",
    "docker-compose.yml",
    "init.ps1",
    "init.sh",
    "justfile",
    "main.go",
    "main.py",
    "manage.py",
}
MANIFEST_KIND_BY_NAME = {
    ".buckconfig": "buck",
    ".devcontainer.json": "devcontainer",
    ".python-version": "python-version",
    ".tool-versions": "tool-versions",
    "BUILD": "bazel-build",
    "BUILD.bazel": "bazel-build",
    "Cargo.toml": "rust",
    "Containerfile": "container",
    "Dockerfile": "container",
    "Gemfile": "ruby",
    "Justfile": "just",
    "Makefile": "make",
    "MODULE.bazel": "bazel",
    "Package.swift": "swift",
    "Pipfile": "python",
    "REPO.bazel": "bazel",
    "WORKSPACE": "bazel",
    "WORKSPACE.bazel": "bazel",
    "build.gradle": "gradle",
    "build.gradle.kts": "gradle",
    "composer.json": "php",
    "global.json": "dotnet",
    "go.mod": "go",
    "go.work": "go",
    "justfile": "just",
    "package.json": "node",
    "pants.toml": "pants",
    "pnpm-workspace.yaml": "node-workspace",
    "pom.xml": "maven",
    "pyproject.toml": "python",
    "requirements.txt": "python",
    "settings.gradle": "gradle",
    "settings.gradle.kts": "gradle",
    "setup.py": "python",
    "terragrunt.hcl": "terraform",
    "turbo.json": "node-workspace",
    "turbo.jsonc": "node-workspace",
    "uv.toml": "python",
}
SBOM_NAME_MARKERS = (
    "bom.json",
    "bom.xml",
    "cyclonedx.json",
    "cyclonedx.xml",
    "sbom.json",
    "sbom.xml",
    "spdx.json",
)
SBOM_SUFFIX_MARKERS = (
    ".cdx.json",
    ".cdx.xml",
    ".cyclonedx.json",
    ".cyclonedx.xml",
    ".spdx",
    ".spdx.json",
    ".spdx.yml",
    ".spdx.yaml",
)


def build_index_report(profile: ProjectProfile) -> dict[str, Any]:
    records, warnings = _file_records(profile)
    class_totals = _class_totals(records)
    manifests = _manifest_records(records)
    source_of_truth = _source_of_truth_records(records)
    review_required = _review_required_records(records)
    components = _component_records(profile.components)
    component_overflow = _component_overflow_report(profile)
    verification_commands = _verification_command_report(profile)
    language_breakdown = _language_breakdown(records)
    entrypoints = _entrypoints(records, profile.verification_commands)
    sboms = _sbom_records(records)
    total_bytes = sum(record["bytes"] for record in records)
    file_coverage = build_file_coverage_report(profile)
    if profile.file_scan_truncated:
        warnings.append(
            f"File scan reached the {profile.file_scan_limit}-file detection limit."
        )
    warnings.extend(file_coverage["warnings"])
    if profile.component_scan_truncated:
        warnings.append(
            "Component inventory selected "
            f"{len(components)} of {profile.component_scan_total} detected "
            f"components at the {profile.component_scan_limit}-component limit."
        )
    if not source_of_truth:
        warnings.append("No high-signal source-of-truth documents were detected.")
    if _verification_missing(profile.verification_commands):
        warnings.append("No runnable verification command was detected.")

    return {
        "schemaVersion": SCHEMA_VERSION,
        "target": {
            "name": profile.name,
            "root": None,
        },
        "mode": "structural",
        "detectedStack": profile.stack,
        "detectedLanguages": list(profile.languages),
        "packageManagers": list(profile.package_managers),
        "execution": {
            "commandsExecuted": False,
            "writesPerformed": False,
        },
        "summary": {
            "fileCount": len(records),
            "byteCount": total_bytes,
            "componentCount": len(components),
            "componentTotalCount": profile.component_scan_total,
            "componentOmittedCount": len(profile.component_overflow),
            "manifestCount": len(manifests),
            "sourceOfTruthCount": len(source_of_truth),
            "reviewRequiredCount": len(review_required),
            "sbomCount": len(sboms),
            "truncated": profile.file_scan_truncated,
            "componentsTruncated": profile.component_scan_truncated,
        },
        "languageBreakdown": language_breakdown,
        "fileClasses": class_totals,
        "components": components,
        "componentOverflow": component_overflow,
        "verificationCommands": verification_commands,
        "manifests": manifests,
        "entrypoints": entrypoints,
        "sourceOfTruth": source_of_truth,
        "sbom": sboms,
        "repoMap": _repo_map(
            profile=profile,
            language_breakdown=language_breakdown,
            class_totals=class_totals,
            components=components,
            manifests=manifests,
            entrypoints=entrypoints,
            source_of_truth=source_of_truth,
            review_required=review_required,
            sboms=sboms,
        ),
        "fileCoverage": file_coverage,
        "reviewRequired": review_required,
        "limits": {
            "maxFiles": profile.file_scan_limit,
            "maxComponents": profile.component_scan_limit,
            "maxExamplesPerClass": MAX_EXAMPLES,
            "textProbeBytes": TEXT_PROBE_BYTES,
        },
        "warnings": warnings,
    }


def format_index_report(report: dict[str, Any]) -> str:
    file_coverage = report["fileCoverage"]
    total_files = (
        file_coverage["totalFileCount"]
        if file_coverage["totalFileCount"] is not None
        else "unknown"
    )
    coverage_status = "complete" if file_coverage["coverageComplete"] else "budget-limited"
    lines = [
        f"Repo index: {report['target']['name']}",
        f"Detected stack: {report['detectedStack']}",
        (
            "Files: "
            f"{report['summary']['fileCount']} "
            f"({report['summary']['byteCount']} bytes)"
        ),
        (
            "File coverage: "
            f"{file_coverage['scannedFileCount']} scanned / {total_files} total "
            f"from {file_coverage['inventorySource']} ({coverage_status})"
        ),
        (
            "Components: "
            f"{report['summary']['componentCount']} included / "
            f"{report['summary']['componentTotalCount']} detected"
        ),
        "",
        "Languages:",
    ]
    for item in report["languageBreakdown"]:
        lines.append(
            f"  - {item['language']}: {item['files']} files, {item['bytes']} bytes"
        )
    lines.append("")
    lines.append("File classes:")
    for item in report["fileClasses"]:
        examples = ", ".join(item["examples"][:5]) if item["examples"] else "none"
        lines.append(
            f"  - {item['class']}: {item['files']} files, "
            f"{item['bytes']} bytes, examples: {examples}"
        )
    if report["sourceOfTruth"]:
        lines.append("")
        lines.append("Source of truth:")
        for item in report["sourceOfTruth"][:10]:
            lines.append(f"  - {item['path']}: {item['kind']}")
    if report["sbom"]:
        lines.append("")
        lines.append("SBOM:")
        for item in report["sbom"][:10]:
            lines.append(f"  - {item['path']}: {item['format']}")
    runnable_commands = [
        item
        for item in report["verificationCommands"]["commands"]
        if item["commandClass"] != "missing"
    ]
    if runnable_commands:
        lines.append("")
        lines.append("Verification commands:")
        for item in runnable_commands[:10]:
            source = item["sourcePath"] or item["sourceType"]
            lines.append(
                f"  - `{item['command']}`: {item['commandClass']} "
                f"({item['scope']}, {source})"
            )
    if report["reviewRequired"]:
        lines.append("")
        lines.append("Review required:")
        for item in report["reviewRequired"][:10]:
            lines.append(f"  - {item['path']}: {item['reason']}")
    if report["warnings"]:
        lines.append("")
        lines.append("Warnings:")
        for warning in report["warnings"]:
            lines.append(f"  - {warning}")
    return "\n".join(lines).rstrip()


def _file_records(profile: ProjectProfile) -> tuple[list[dict[str, Any]], list[str]]:
    records: list[dict[str, Any]] = []
    warnings: list[str] = []
    for relative in profile.files:
        path = profile.root / path_from_relative_text(relative)
        if not is_inside_root(path, profile.root):
            warnings.append(f"Skipped path outside target root: {relative}.")
            continue
        try:
            stat = path.stat()
        except OSError:
            warnings.append(f"Could not stat file: {relative}.")
            continue
        if not path.is_file() or path.is_symlink():
            continue
        text_probe = _text_probe(path, relative)
        language = _language_for_path(relative)
        classes = _classes_for_path(relative, language, text_probe)
        records.append(
            {
                "path": _normalize_relative(relative),
                "bytes": stat.st_size,
                "language": language,
                "classes": classes,
                "textProbe": text_probe,
            }
        )
    return records, warnings


def _class_totals(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    totals: dict[str, dict[str, Any]] = {
        file_class: {"class": file_class, "files": 0, "bytes": 0, "examples": []}
        for file_class in FILE_CLASS_ORDER
    }
    for record in records:
        for file_class in record["classes"]:
            total = totals[file_class]
            total["files"] += 1
            total["bytes"] += record["bytes"]
            if len(total["examples"]) < MAX_EXAMPLES:
                total["examples"].append(record["path"])
    return [totals[file_class] for file_class in FILE_CLASS_ORDER]


def _language_breakdown(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    totals: dict[str, dict[str, int]] = defaultdict(lambda: {"files": 0, "bytes": 0})
    for record in records:
        language = record["language"]
        totals[language]["files"] += 1
        totals[language]["bytes"] += record["bytes"]
    return [
        {
            "language": language,
            "files": values["files"],
            "bytes": values["bytes"],
        }
        for language, values in sorted(
            totals.items(),
            key=lambda item: (-item[1]["files"], item[0]),
        )
    ]


def _component_records(components: tuple[str, ...]) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for component in components:
        path, markers = _parse_component(component)
        records.append(
            {
                "path": path,
                "markers": markers,
                "group": _component_group(path),
                "rankReason": _component_rank_reason(path, markers),
                "confidence": "high" if markers else "medium",
                "source": "manifest",
            }
        )
    return records


def _component_overflow_report(profile: ProjectProfile) -> dict[str, Any]:
    omitted = _component_records(profile.component_overflow)
    return {
        "schemaVersion": "harnessforge.componentOverflow.v1",
        "limit": profile.component_scan_limit,
        "includedCount": len(profile.components),
        "totalCount": profile.component_scan_total,
        "omittedCount": len(profile.component_overflow),
        "truncated": profile.component_scan_truncated,
        "omittedExamples": omitted[:20],
        "groupCounts": _component_group_counts(
            _component_records(profile.components + profile.component_overflow)
        ),
        "recommendedAction": (
            "Raise --component-limit or add important omitted boundaries manually."
            if profile.component_scan_truncated
            else "none"
        ),
    }


def _verification_command_report(profile: ProjectProfile) -> dict[str, Any]:
    records = [
        {
            "command": record.command,
            "commandClass": record.command_class,
            "scope": record.scope,
            "sourceType": record.source_type,
            "sourcePath": record.source_path,
            "sourceDetail": record.source_detail,
            "confidence": record.confidence,
        }
        for record in profile.verification_command_records
    ]
    if not records:
        records = [
            {
                "command": command,
                "commandClass": (
                    "missing" if _verification_missing((command,)) else "other"
                ),
                "scope": "unknown",
                "sourceType": "legacy",
                "sourcePath": "",
                "sourceDetail": "unattributed command",
                "confidence": "low",
            }
            for command in profile.verification_commands
        ]
    runnable = [record for record in records if record["commandClass"] != "missing"]
    class_counts: dict[str, int] = defaultdict(int)
    source_counts: dict[str, int] = defaultdict(int)
    for record in records:
        class_counts[str(record["commandClass"])] += 1
        source_counts[str(record["sourceType"])] += 1
    return {
        "schemaVersion": "harnessforge.verificationCommands.v1",
        "commands": records,
        "summary": {
            "commandCount": len(runnable),
            "missing": not runnable,
            "classes": dict(sorted(class_counts.items())),
            "sourceTypes": dict(sorted(source_counts.items())),
            "lowConfidenceCount": sum(
                1 for record in records if record["confidence"] == "low"
            ),
        },
    }


def _component_group_counts(components: list[dict[str, Any]]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for component in components:
        group = str(component["group"])
        counts[group] = counts.get(group, 0) + 1
    return dict(sorted(counts.items()))


def _component_group(path: str) -> str:
    if path == ".":
        return "root"
    first_segment = path.split("/", 1)[0]
    if first_segment in {"apps", "packages", "services", "crates"}:
        return "workspace"
    if first_segment in {"src", "cmd", "pkg", "lib"}:
        return "source"
    if first_segment in {"tools", "scripts", "hack"}:
        return "tooling"
    if first_segment in {"test", "tests", "spec"}:
        return "tests"
    if first_segment in {"docs", "site"}:
        return "docs"
    if first_segment in {"examples", "samples"}:
        return "examples"
    if first_segment in {"vendor", "third_party", "external"}:
        return "vendor"
    return "other"


def _component_rank_reason(path: str, markers: list[str]) -> str:
    group = _component_group(path)
    if group == "root":
        return "root manifest boundary"
    if group in {"workspace", "source", "tooling"}:
        return f"{group} component boundary"
    if "BUILD" in markers or "BUILD.bazel" in markers:
        return "build graph boundary"
    if group in {"docs", "examples", "vendor"}:
        return f"lower-priority {group} boundary"
    return "manifest boundary"


def _manifest_records(records: list[dict[str, Any]]) -> list[dict[str, str]]:
    manifests: list[dict[str, str]] = []
    for record in records:
        path = record["path"]
        name = PurePosixPath(path).name
        if name not in COMPONENT_MARKERS and name not in MANIFEST_KIND_BY_NAME:
            if not name.endswith((".csproj", ".fsproj", ".vbproj", ".sln", ".slnx")):
                continue
        manifests.append(
            {
                "path": path,
                "kind": MANIFEST_KIND_BY_NAME.get(name, _manifest_kind(name)),
                "directory": _directory_for(path),
            }
        )
    return manifests[:120]


def _entrypoints(
    records: list[dict[str, Any]], verification_commands: tuple[str, ...]
) -> list[dict[str, str]]:
    entrypoints: list[dict[str, str]] = []
    for record in records:
        path = record["path"]
        pure = PurePosixPath(path)
        name = pure.name
        if (
            name in ENTRYPOINT_NAMES
            or path.startswith(".github/workflows/")
            or (
                path.startswith("scripts/")
                and pure.suffix.lower() in {".py", ".ps1", ".sh"}
            )
        ):
            entrypoints.append(
                {
                    "path": path,
                    "kind": _entrypoint_kind(path),
                    "source": "file",
                }
            )
    for index, command in enumerate(verification_commands):
        if _verification_missing((command,)):
            continue
        entrypoints.append(
            {
                "path": "",
                "kind": "verification-command",
                "source": f"detected:{index}",
                "command": command,
            }
        )
    return entrypoints[:120]


def _sbom_records(records: list[dict[str, Any]]) -> list[dict[str, str]]:
    sboms: list[dict[str, str]] = []
    for record in records:
        sbom_format, evidence = _sbom_format(record["path"], record["textProbe"])
        if not sbom_format:
            continue
        sboms.append(
            {
                "path": record["path"],
                "format": sbom_format,
                "source": "existing-file",
                "evidence": evidence,
            }
        )
    return sboms[:50]


def _source_of_truth_records(records: list[dict[str, Any]]) -> list[dict[str, str]]:
    result: list[dict[str, str]] = []
    for record in records:
        path = record["path"]
        pure = PurePosixPath(path)
        lower_name = pure.name.lower()
        lower_parts = {part.lower() for part in pure.parts}
        if path in INSTRUCTION_FILES:
            result.append(
                {
                    "path": path,
                    "kind": "agent-instructions",
                    "reason": "Agent instruction surface.",
                }
            )
        elif lower_name in SOURCE_OF_TRUTH_NAMES and (
            lower_parts & SOURCE_OF_TRUTH_PARTS or lower_name == "readme.md"
        ):
            result.append(
                {
                    "path": path,
                    "kind": "project-doc",
                    "reason": "High-signal project documentation name.",
                }
            )
        elif pure.parts and pure.parts[0] in {".specify", "specs", "aspec"}:
            result.append(
                {
                    "path": path,
                    "kind": "spec-system",
                    "reason": "Structured specification surface.",
                }
            )
    return _dedupe_records(result)[:120]


def _review_required_records(records: list[dict[str, Any]]) -> list[dict[str, str]]:
    result: list[dict[str, str]] = []
    for record in records:
        if (
            {"docs", "harness", "config"} & set(record["classes"])
            and "review required" in record["textProbe"].lower()
        ):
            result.append(
                {
                    "path": record["path"],
                    "reason": "Contains REVIEW REQUIRED marker.",
                }
            )
    return result[:120]


def _classes_for_path(
    relative: str, language: str, text_probe: str
) -> tuple[str, ...]:
    pure = PurePosixPath(relative)
    name = pure.name
    lower_name = name.lower()
    lower_parts = {part.lower() for part in pure.parts}
    classes: list[str] = []
    if language in SOURCE_LANGUAGES:
        classes.append("source")
    if (
        {"test", "tests", "__tests__"} & lower_parts
        or lower_name.startswith("test_")
        or lower_name.endswith("_test.py")
        or lower_name.endswith((".spec.ts", ".spec.tsx", ".test.ts", ".test.tsx"))
        or lower_name.endswith(("_test.go", "_test.rs"))
    ):
        classes.append("test")
    if language == "docs" or {"doc", "docs", "documentation"} & lower_parts:
        classes.append("docs")
    if _is_generated(relative, text_probe):
        classes.append("generated")
    if VENDOR_PARTS & lower_parts:
        classes.append("vendor")
    if relative.startswith(".github/workflows/"):
        classes.append("workflow")
    if relative in INSTRUCTION_FILES or relative.startswith("docs/harness/"):
        classes.append("harness")
    if (
        name in COMPONENT_MARKERS
        or name in MANIFEST_KIND_BY_NAME
        or PurePosixPath(relative).suffix.lower()
        in {".json", ".toml", ".yaml", ".yml", ".ini", ".cfg", ".conf"}
    ):
        classes.append("config")
    if _sbom_format(relative, text_probe)[0]:
        classes.append("sbom")
    if not classes:
        classes.append("other")
    return tuple(file_class for file_class in FILE_CLASS_ORDER if file_class in classes)


def _repo_map(
    *,
    profile: ProjectProfile,
    language_breakdown: list[dict[str, Any]],
    class_totals: list[dict[str, Any]],
    components: list[dict[str, Any]],
    manifests: list[dict[str, str]],
    entrypoints: list[dict[str, str]],
    source_of_truth: list[dict[str, str]],
    review_required: list[dict[str, str]],
    sboms: list[dict[str, str]],
) -> dict[str, Any]:
    class_by_name = {item["class"]: item for item in class_totals}
    primary_languages = [
        item
        for item in language_breakdown
        if item["language"] not in {"other", "json", "yaml", "toml"}
    ][:5]
    manifest_counts: dict[str, int] = defaultdict(int)
    for item in manifests:
        manifest_counts[item["kind"]] += 1
    boundaries = [
        {
            "class": name,
            "files": class_by_name[name]["files"],
            "examples": class_by_name[name]["examples"][:5],
        }
        for name in (
            "source",
            "test",
            "docs",
            "workflow",
            "harness",
            "generated",
            "vendor",
            "sbom",
        )
        if class_by_name.get(name, {}).get("files", 0)
    ]
    verification = _verification_command_report(profile)
    verification_commands = [
        record["command"]
        for record in verification["commands"]
        if record["commandClass"] != "missing"
    ]
    unknowns: list[str] = []
    if not source_of_truth:
        unknowns.append("No high-signal project source-of-truth document detected.")
    if not components:
        unknowns.append("No component boundary markers detected.")
    if not verification_commands:
        unknowns.append("No runnable verification command detected.")
    if not sboms:
        unknowns.append("No existing project-owned SBOM detected.")
    return {
        "schemaVersion": "harnessforge.repoMap.v1",
        "mode": "structural",
        "summary": {
            "target": profile.name,
            "detectedStack": profile.stack,
            "primaryLanguages": [
                {
                    "language": item["language"],
                    "files": item["files"],
                }
                for item in primary_languages
            ],
            "componentCount": len(components),
            "sourceOfTruthCount": len(source_of_truth),
            "manifestCount": len(manifests),
            "sbomCount": len(sboms),
            "reviewRequiredCount": len(review_required),
        },
        "components": components[:20],
        "sourceOfTruth": source_of_truth[:10],
        "manifestKinds": [
            {"kind": kind, "count": count}
            for kind, count in sorted(
                manifest_counts.items(),
                key=lambda item: (-item[1], item[0]),
            )[:20]
        ],
        "entrypoints": entrypoints[:20],
        "boundaries": boundaries,
        "sbom": sboms[:10],
        "verification": {
            "schemaVersion": verification["schemaVersion"],
            "commands": verification["commands"][:10],
            "missing": not verification_commands,
            "summary": verification["summary"],
        },
        "reviewRequired": review_required[:10],
        "unknowns": unknowns,
        "notes": [
            "Structural map only; no target commands were executed.",
            "Paths are target-relative and no private code summaries are included.",
            "Existing SBOM files are cited as evidence; HarnessForge did not generate an SBOM.",
        ],
    }


def _is_generated(relative: str, text_probe: str) -> bool:
    pure = PurePosixPath(relative)
    lower_name = pure.name.lower()
    lower_parts = {part.lower() for part in pure.parts}
    return (
        bool(GENERATED_PARTS & lower_parts)
        or any(marker in lower_name for marker in GENERATED_NAME_MARKERS)
        or _comment_header_has_marker(text_probe, GENERATED_TEXT_MARKERS)
    )


def _sbom_format(relative: str, text_probe: str) -> tuple[str, str]:
    pure = PurePosixPath(relative)
    lower_name = pure.name.lower()
    lower_path = relative.lower()
    lower_probe = text_probe[:2048].lower()
    name_match = lower_name in SBOM_NAME_MARKERS or any(
        lower_path.endswith(marker) for marker in SBOM_SUFFIX_MARKERS
    )
    if '"bomformat"' in lower_probe and "cyclonedx" in lower_probe:
        return "cyclonedx", "bomFormat marker"
    if "<bom" in lower_probe and (
        "cyclonedx" in lower_probe or "cyclonedx.org/schema" in lower_probe
    ):
        return "cyclonedx", "CycloneDX XML marker"
    if '"spdxversion"' in lower_probe or lower_probe.lstrip().startswith(
        "spdxversion:"
    ):
        return "spdx", "SPDX version marker"
    if name_match:
        if "spdx" in lower_path:
            return "spdx", "SPDX filename marker"
        if "cdx" in lower_path or "cyclonedx" in lower_path or "bom" in lower_name:
            return "cyclonedx", "CycloneDX filename marker"
        return "unknown", "SBOM filename marker"
    return "", ""


def _language_for_path(relative: str) -> str:
    pure = PurePosixPath(relative)
    name = pure.name
    if name in {"Dockerfile", "Containerfile"}:
        return "dockerfile"
    if name in {"Makefile", "makefile"}:
        return "make"
    if name in {"Justfile", "justfile"}:
        return "just"
    if name in {"BUILD", "WORKSPACE"}:
        return "starlark"
    if name.endswith((".csproj", ".fsproj", ".vbproj", ".sln", ".slnx")):
        return "dotnet"
    return LANGUAGE_BY_SUFFIX.get(pure.suffix.lower(), "other")


def _text_probe(path: Path, relative: str) -> str:
    suffix = PurePosixPath(relative).suffix.lower()
    if suffix not in TEXT_SUFFIXES and PurePosixPath(relative).name not in {
        "Dockerfile",
        "Containerfile",
        "Justfile",
        "Makefile",
        "justfile",
    }:
        return ""
    try:
        with path.open("rb") as handle:
            data = handle.read(TEXT_PROBE_BYTES)
    except OSError:
        return ""
    return data.decode("utf-8", errors="ignore")


def _comment_header_has_marker(text: str, markers: tuple[str, ...]) -> bool:
    for line in text.splitlines()[:20]:
        stripped = line.strip()
        if not stripped:
            continue
        lower = stripped.lower()
        is_comment = lower.startswith(
            ("#", "//", "/*", "*", "<!--", "--", ";")
        )
        if not is_comment:
            return False
        if any(marker in lower for marker in markers):
            return True
    return False


def _parse_component(component: str) -> tuple[str, list[str]]:
    if component.endswith(")") and " (" in component:
        path, marker_text = component[:-1].split(" (", 1)
        markers = [item.strip() for item in marker_text.split(",") if item.strip()]
        return path, markers
    return component, []


def _manifest_kind(name: str) -> str:
    if name.endswith((".csproj", ".fsproj", ".vbproj", ".sln", ".slnx")):
        return "dotnet"
    return "manifest"


def _entrypoint_kind(path: str) -> str:
    if path.startswith(".github/workflows/"):
        return "github-workflow"
    name = PurePosixPath(path).name
    if name in {"action.yml", "action.yaml"}:
        return "github-action"
    if name in {
        "Dockerfile",
        "Containerfile",
        "docker-compose.yml",
        "docker-compose.yaml",
    }:
        return "container"
    if name in {"Makefile", "makefile", "Justfile", "justfile"}:
        return "task-runner"
    if name.endswith(".ps1"):
        return "powershell-script"
    if name.endswith(".sh"):
        return "shell-script"
    if name.endswith(".py"):
        return "python-script"
    return "entrypoint"


def _directory_for(relative: str) -> str:
    parent = PurePosixPath(relative).parent.as_posix()
    return "." if parent == "." else parent


def _normalize_relative(relative: str) -> str:
    return path_from_relative_text(relative).as_posix()


def _verification_missing(commands: tuple[str, ...]) -> bool:
    return not commands or all(
        command.startswith("REVIEW REQUIRED:") for command in commands
    )


def _dedupe_records(records: list[dict[str, str]]) -> list[dict[str, str]]:
    seen: set[str] = set()
    deduped: list[dict[str, str]] = []
    for record in records:
        key = f"{record.get('path', '')}\0{record.get('kind', '')}"
        if key in seen:
            continue
        seen.add(key)
        deduped.append(record)
    return deduped
